"""Data classes for self-healing extraction strategies."""

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ExtractionTask:
    """Describes what data needs to be extracted from a page.

    Each healable scraping operation is defined as an ExtractionTask
    with enough context for an LLM to generate extraction code.
    """

    task_id: str
    """Unique identifier, e.g. 'cgv_imax_title', 'watcha_rating'."""

    url: str
    """The URL being scraped (for context in LLM prompts)."""

    description: str
    """Human-readable description of what to extract.

    This is the core of the LLM prompt. Be specific about what
    the data looks like and where it appears on the page.
    """

    expected_type: str
    """What the result should look like: 'string', 'float', 'list[dict]'."""

    validation_hint: str
    """How to validate the result, e.g. 'Korean movie title, 2-30 chars'."""

    example_result: str
    """An example of a valid result, e.g. '인터스텔라' or '3.5'."""


@dataclass
class ExtractionStrategy:
    """A strategy for extracting data, generated by LLM or hardcoded.

    The js_code is executed via Playwright's page.evaluate() and must
    return the extracted value or null.
    """

    task_id: str
    js_code: str
    """JavaScript code to evaluate in page context."""

    version: int = 0
    """Incremented each time a new strategy is generated."""

    created_at: str = ""
    """ISO 8601 timestamp."""

    source: str = "llm"
    """'hardcoded' for built-in strategies, 'llm' for AI-generated."""
